### ISSUE TITLE
[BUG] Cant use HITrava for the last 3 days

### ISSUE THREAD

**Issue by kosovarpt** [CTHRU/Hitrava#11]
I've always used HiTrava with standard command "Run_Hitrava.cmd". For the last 3 days I cant use anymore. 
I send a screenshot of the error!

![Capture](https://user-images.githubusercontent.com/65366666/81976916-252cc680-9621-11ea-9e28-f488f86f6140.PNG)

**Comment by GeitV** [comment]
Have the same error, if needed, can provide my zip file for debugging

**Comment by CTHRU** [comment]
You stumbled upon an activity sport type that is currently unknown to Hitrava. You also discovered a small bug that the program doesn't accept unknown sport types when they appear in the header data of the activity. I will correct that.

As for the first part, I would like to investigate if this (unknown) sport type could be supported. You could help me with that by providing me additional information about your activity of May 5th, 2020.

- Option 1 (easiest for me, but you need to feel alright with temporarily sharing that specific activity data with me, I use it only temporarily to debug/add the feature to support it): Please add the file below to a comment in this ticket (you can just drag and drop it into your new comment screen). I will inform you when i have a local copy, you can then remove it again from your comment.
> _{your Hitrava installation folder}_\output\Hitrack_20200505_101253.json

- Option 2: Open the file above in a text editor (e.g. notepad). You should see  something like:
> [{"motionPathData": [{"sportType": ?,
I would require the number that appears where the question mark (?) is in the line above.

In both cases, please let me know what the sport type is of the activity as it appears in Huawei Health.

Thank you.

**Comment by CTHRU** [comment]
@GeitV, I'm online now, if you could share your ZIP file, that would be great.

**Comment by kosovarpt** [comment]
I sent to you one printscreen of all my ativivities from Huawei Health and
the zip file.

A sexta, 15 de mai de 2020, 10:43, Christoph Vanthuyne <
notifications@github.com> escreveu:

**Comment by stevellion** [comment]
I'm also getting the same error.
Sport type is 117 - Recorded on Watch GT2 - It's marked as "Other".
(I think is was chasing the kids.... :-)  ) - Sent you a coffee too!

**Comment by kosovarpt** [comment]
One the activities from 05 of May was CrossFit. All the rest was exterior
runinng

A sexta, 15 de mai de 2020, 10:43, Christoph Vanthuyne <
notifications@github.com> escreveu:

**Comment by kosovarpt** [comment]
Can you confirm that you receive the files? Ty

**Comment by GeitV** [comment]
"sportType": 103
Which corresponds to "indoor cycle"
Not something I want to sync with Strava, but might want to get fixed still :smile:

**Comment by CTHRU** [comment]
> 
> 
> Can you confirm that you receive the files? Ty

@kosovarpt I'm sorry, I didn't receive the files (or must have missed them in one of your comments). I think you tried to reply via mail, unfortunately, that doesn't add the attachments on GitHub (I assume). Could you try again by going to the GitHub issue page and add a new comment there. You can drag the file to the comment window.

**Comment by CTHRU** [comment]
@GeitV OK, thanks for the info for the 103 too. If you want, I can see whether it would be possible to sync any useful data (provided you're ok to temporarily share the JSON export of the activity as explained [above](https://github.com/CTHRU/Hitrava/issues/11#issuecomment-629140019)

**Comment by GeitV** [comment]
I've never done indoor cycling so this must've been some kind of accidental activity start from my end. But here you go
[HiTrack_20190917_154322.zip](https://github.com/CTHRU/Hitrava/files/4633729/HiTrack_20190917_154322.zip)

**Comment by kosovarpt** [comment]
![Screenshot_20200515_104550_com huawei health](https://user-images.githubusercontent.com/65366666/82039757-65318f00-969d-11ea-9bee-69c342039aba.jpg)
[0070351000022330544.20200514090407.o47StLc5nA0kt2qTzEr1EhuF1ibXuHHv.zip](https://github.com/CTHRU/Hitrava/files/4633728/0070351000022330544.20200514090407.o47StLc5nA0kt2qTzEr1EhuF1ibXuHHv.zip)
Ok, I sent via email. I didn't no that was no possible. Here are them in comments. Ty

**Comment by CTHRU** [comment]
> 
> 
> I've never done indoor cycling so this must've been some kind of accidental activity start from my end. But here you go
> [HiTrack_20190917_154322.zip](https://github.com/CTHRU/Hitrava/files/4633729/HiTrack_20190917_154322.zip)

@GeitV - got the file, you can remove it from your post if you want.

**Comment by kosovarpt** [comment]
But now, I after thinking I will delete that activity "Croosfit" because I dont want that in my Strava too. :P

**Comment by CTHRU** [comment]
@kosovarpt - OK, thank you, I got the file, you can remove it from your post if you want. Will see if anything is possible with the crossfit activity.

**Comment by stevellion** [comment]
I do also do quite a bit of Indoor Cycling (well, will, when the lockdown is over) - Trying to figure out what the JSON code is for you.

**Comment by stevellion** [comment]
Just found all the codes in my big 1 JSON file (ID'd versus the calories burned on my phone)
SportType   Activity
3		Outdoor Cycle
5		Walk
4		Outdoor Run
102		Indoor Swim
103		Indoor Cycle
111		Cross Trainer/Elyptical
117		Other

**Comment by stevellion** [comment]
> > I'm also getting the same error.
> > Sport type is 117 - Recorded on Watch GT2 - It's marked as "Other".
> > (I think is was chasing the kids.... :-) ) - Sent you a coffee too!
> 
> @stevellion Thank you so much for the coffee! Much appreciated.
> 
> Ok, so I officially add sport type 117 as 'Chasing the kids' then? :-)
> 
> I'll prepare the code to accept 117 and wait for an example file to see if additional changes would be necessary.

[HiZip.zip](https://github.com/CTHRU/Hitrava/files/4634093/HiZip.zip)

please remove when downloaded for debugging.

**Comment by CTHRU** [comment]
@stevellion - thanks for the copy, I have a temp copy for the debugging. You can remove the link from your comment above. I will delete my temp copy after testing.

**Comment by CTHRU** [comment]
Ok, an update on the situation. Your files helped me reproduce the error.
The good news, I will release a patch to resolve the issue that the programs stops when it encounters an activity type it doesn't recognize.
Unfortunately, none of the 'new' activity types you helped to discover (Indoor Cycle, Cross Trainer, Other, CrossFit) produces a usable result for now. I added them to the unsupported activity types for now and will look if adjustments can be made to support them in a future release (might take some time, though).

I propose to close this ticket with the release of the next version. I will create a separate ticket to analyze / implement support for the above mentioned activity types.
