### ISSUE TITLE
[FEATURE] Investigate / Support activity types Indoor Cycle / Cross Trainer / Other / CrossFit

### ISSUE THREAD

**Issue by CTHRU** [CTHRU/Hitrava#12]
See also #11.

Conversion of Indoor Cycle / Cross Trainer / Other / CrossFit activities produces unreliable conversion data. Analyze feasibility / support these activity types for conversion.

**Comment by stevellion** [comment]
From what I can see Indoor Cycle, Crosstrainer & Other are all just tracking heart beat, time and total calories.

The primary value is Calories (vs Distance for all others).

**Comment by CTHRU** [comment]
@stevellion Yes, you're right. The main things I already noticed are the negative speed records (indoor) to be ignored (which currently cause negative distances in the track points) and some unuseful heart rate data to be ignored. Also need to check on Strava side how each type can best be 'disguised' (Strava has limited set of supported sport types).
