### ISSUE TITLE
[FEATURE] Conversion from .tar/ individual HiTrack_ file results in a .tcx filename with unix timestamp datetime instead of human readable

### ISSUE THREAD

**Issue by dany123** [CTHRU/Hitrava#18]
**Is your feature request related to a problem? Please describe.**
When converting a single file named "HiTrack_1594228021000159422864000030001" the output file is named "HiTrack_1594228021000159422864000030001.tcx" which is pretty ugly to read. 
I can use a format of --output_file_prefix "%Y-%m-%d %H-%M-%S " to get an output of "2020-07-08 17-07-02 HiTrack_1594228021000159422864000030001.tcx" but this is way too long and still ugly. 

The .zip from huawei data is nicely converted to files with format "HiTrack_20200708_200701_001.tcx" which is very readable, and sorts nicely in explorers (also converted to correct timezone, nice touch there!).

**Describe the solution you'd like**
My request is to treat HiTrack files the same as .json type for output, so something like this: 
HiTrack_"timestamp_start""timestamp_end"  -->  HiTrack_YYYYMMDD_HHMMSS.tcx 

Note: same request for .tar processing.

**Additional context**
For context: I requested my data from huawei a few weeks ago and succesfully used Hitrava on that .zip to get the activities. Today I wanted to re-redownload the latest data but they have a timeout period in which you can't re-request your data again so I used an android emulator, rooted it, installed huawei health in it and got my data this way after syncing to cloud. The result wasn't as nicely as a few weeks back and I think this change would be very quick and useful.

Thanks,
Daniel

**Comment by CTHRU** [comment]
Good suggestion, and I like your creative way to get to the files. 

I will add the functionality in the next release (expect it somewhere in the next week)

**Comment by dany123** [comment]
Thank you!
