### ISSUE TITLE
[SUPPORT] Series of errors when I launch Hitrava.py

### ISSUE THREAD

**Issue by ragno28** [CTHRU/Hitrava#23]
I got a series of errore when I try to execute the program, I'll link a couple of screenshot of the prompt and the folder where i have Hitrava installed.
Thank you in advance for helping me out.
![Command_prompt](https://user-images.githubusercontent.com/69846571/90499501-ed667b00-e149-11ea-8aab-926bce3a4782.PNG)
![Folder](https://user-images.githubusercontent.com/69846571/90499546-f8b9a680-e149-11ea-948b-9f43636e9f9b.PNG)

**Comment by CTHRU** [comment]
It could be that the JSON file the program is looking for, is not there. could you check [this post in issue 9](https://github.com/CTHRU/Hitrava/issues/9#issuecomment-623128232) and report back?

**Comment by CTHRU** [comment]
A while ago, a similar issue was opened in #14. I could reproduce the error by creating an invalid ZIP file (I just created a text file and renamed it this_is_no_zip.zip). I got the same error. I just released an update and I added a logging message when python checks the integrity of the ZIP file in the --zip argument.

Thank you for closing this issue if there was indeed a problem with your ZIP file.

**Comment by ragno28** [comment]
So I tried to make a my_run_hitrava.cmd as you suggested in #9 but it ended with the same error.
After that I checked the json file in the HiZip.zip and it looked similar to the others that I've seen in #9 .
I was thinking of switching back to python 3.7 cause actually I downloaded the 3.8.5

Example of what I find in motion path detail data.json:
[{"totalSteps":2090,"recordId":"lE0LCAAAAAACAAAAoB4jT24BAAA=","totalStoreys":0,"appType":1,"vendor":"GOOGLE","partTimeMap":{"1.0":1603.0,"2.0":3137.0,"3.0":4997.0,"4.0":7195.0},"abnormalTrack":0,"realStoreys":0,"startTime":1573285732000,"attribute":"HW_EXT_TRACK_DETAIL@istp=lbs;k=0;lat=46.102848845440434;lon=8.256683445987887;alt=1.1782990870004883E8;t=1.573285733E9;\ntp=lbs;k=1;lat=46.102848845440434;lon=8.256681411482703;alt=1.1783110700009766E8;t=1.573285734E9;\ntp=lbs;k=2;lat=46.102848845440434;lon=8.256680394230111;alt=1.1783230530014649E8;t=1.573285735E9;\ntp=lbs;k=3;lat=46.102848845440434;lon=8.25667632521955;alt=1.1783350360019532E8;t=1.573285736E9;\ntp=lbs;k=4;lat=46.102848845440434;lon=8.256668187198812;alt=1.178347019E8;t=1.573285737E9;\ntp=lbs;k=5;lat=46.10284884544044;lon=8.256655517780516;alt=1.178358999E8;t=1.573285738E9;\ntp=lbs;k=6;lat=46.10284884544044;lon=8.256647009850235;alt=1.178370979E8;t=1.573285739E9;\ntp=lbs;k=7;lat=46.10284884544044;lon=8.25663720723512;alt=1.178382959E8;t=1.57328574E9;\ntp=lbs;k=8;lat=46.10284884544044;lon=8.256624907726644;alt=1.178394939E8;t=1.573285741E9;\ntp=lbs;k=9;lat=46.102848105620325;lon=8.256611775920842;alt=1.178406919E8;t=1.573285742E9;\ntp=lbs;k=10;lat=46.102848105620325;lon=8.25659864411518;alt=1.178418899E8;t=1.573285743E9;\ntp=lbs;k=11;lat=46.102848105620325;lon=8.2565860671746;alt=1.178430879E8;t=1.573285744E9;\ntp=lbs;k=12;lat=46.102847365800216;lon=8.256573582711654;alt=1.178442859E8;t=1.573285745E9;\ntp=lbs;k=13;lat=46.10284588616;lon=8.25656035842878;alt=1.178454839E8;t=1.573285746E9;\ntp=lbs;k=14;lat=46.10284366669962;lon=8.256547504056151;alt=1.178466819E8;t=1.573285747E9;\ntp=lbs;k=15;lat=46.10284144723925;lon=8.256534187294104;alt=1.1784788030039063E8;t=1.573285748E9;\ntp=lbs;k=16;lat=46.10283922777887;lon=8.256520500622093;alt=1.1784907870078126E8;t=1.573285749E9;\ntp=lbs;k=17;lat=46.102837008318495;lon=8.256506444037875;alt=1.1785027710117188E8;t=1.57328575E9;\ntp=lbs;k=18;lat=46.10283552867818;lon=8.256492294976164;alt=1.178514755015625E8;t=

**Comment by CTHRU** [comment]
Python 3.8.5 should not be an issue (I test with 3.5.1, 3.7.6 and 3.8.5). The data in the JSON file is also OK, so we'll have to look somewhere else.

I assume you tried again with the latest 3.5.3 release of yesterday and got the same error? The beginning of the logging should look something like this (thanks for verifying versions):

>[date and time] - INFO - main - Hitrava version _**3.5.3**_ (build 2008.1801) started with arguments ['--zip', 'HiZip.zip', '--json_export']
>[date and time] - INFO - main - Running on Python version _**3.8.5**_

If the log isn't too long, please post it again here, maybe this can help out in finding the root cause. If you wouldn't mind (temporarily) sharing the ZIP file, I'll be glad to check what's going on.

**Comment by ragno28** [comment]
Ok I solved the problem. 
In fact It was a very stupid thing, I named the zip file "HiZip.zip" but Windows interpret It as "HiZip.zip.zip" so I just needed to name it simply "HiZip".
Thank You for helping me out, and You did a really cool tool. 
I'm still astonished by Huawei for don't let extract the .gpx from the app.
