### ISSUE TITLE
Using "HiHealth" in the future.

### ISSUE THREAD

**Issue by mbraeutig** [CTHRU/Hitrava#26]
Hi,

please have a look at:
https://forums.developer.huawei.com/forumPortal/en/topicview?tid=0201339947472930085&fid=0101187876626530001
and here:
https://developer.huawei.com/consumer/en/hms/huaweihealth/

Maybe you can use this in the future or ?

I do not understand all,
but i think, there is a little bit hope, so we need not every time request our data.

greet and thanks
Michael

**Comment by CTHRU** [comment]
Thanks for the heads up, and that is indeed good news.
I already looked into that API, but it is (was) not possible to get the detailed data via the existing API (except for some summary information of the activity).

**Comment by CrooZER** [comment]
Looks like Huawei has plans to release support of Huawei Health via Restful in October. If they do it (mb a bit later), we will have access to all records data(incl. GPS and heart rate). It would be great if you try to make it possible to get this data. I have registered as a developer to their API system, just want to try if it works.
According to their information, Android developers have access already.
----- From forum
Only the Health kit can provide the HTTP RESTful API. The  Hihealth kit don't support it.

But now Health Kit could not get the data from the Health APP.

This function we will provide about October, Please wait patiently.
https://forums.developer.huawei.com/forumPortal/en/topicview?tid=0201319092625460246&fid=0101187876626530001

**Comment by kelvindavies11** [comment]
Hi team,
Firstly thank you for the service you are providing - Top Marks!!!

I'm still reading through the supporting documentation, but Hauwei seem to be making progress with providing access to activity data :-)

Activity types are now available here - https://developer.huawei.com/consumer/en/doc/activity-types-0000001050071667-V5

I'm struggling to find specifics about available GPS activity data, but the following scope page suggests you get use some calls to get activity data (https://www.huawei.com/healthkit/activityrecord.read) and also location data. - https://developer.huawei.com/consumer/en/doc/scope-list-0000001055419280-V5
