### ISSUE TITLE
[ENHANCEMENT] Provide command line argument option to generate altitude data for every record in the TCX file to support 3rd party services.

### ISSUE THREAD

**Issue by muenkel** [CTHRU/Hitrava#27]
Hi,
I'm using the Honor Magic Watch 2 to log GPS positions and altitudes. I've found out, that not every track point in a HiTrack* file  has an altitude entry. Therefore after the conversion with Hitrava.py into a tcx-file not every Trackpoint element has an  AltitudeMeters element. This caused problems, if the tcx-file is loaded in a program like QMapShack, to visualize the whole track on a map, because in these programs the altitude of every track point without an altitude is set to zero. So, even if you've walked in a flat area, it is possible that the program calculates that you've climbed on a hill with thousands of meters. To overcome this it would be nice if Hitrava has the possibility to interpolate the altitudes for the track points without an altitude value.

**Comment by CTHRU** [comment]
Thanks for your report, I understand your issue. Thing is I'm not sure whether TCX forces or compels to have altitude information for every trackpoint. For now, I assume this isn't necessarily the case. I use ([GPXSee](https://www.gpxsee.org)) to check whether Hitrava converted TCX files are readable, and the 'Elevation' information is represented in a correct fashion for an activity with altitude data.  

I could add a command line argument to 'simulate' altitude information with every trackpoint in the generated TCX, but I'd rather not if it is not a TCX requirement.

I see following options for now:
- If you find information that TCX files would require altitude info with every trackpoint when altitude data is available, I can evaluate to implement a solution like described above.
- I advise you to check with the makers of QMapShack (if you didn't already) whether it's not better if they would be able to handle TCX files with altitude information in a similar fashion like GPXSee (provided that the assumption in the previous point is not a requirement).

If you have more info / other thoughts, just let me know here.

**Comment by muenkel** [comment]
Hi,

thanks for your answer and thanks for the nice tool.

I've seen the problem also in other programs, e.g. the web app 
https://www.mygpsfiles.com/app/. In this app there is a small elevation 
graphic in the left button corner. In this graphic the altitudes are 
only shown, if the tcx-file has altitude information for all trackpoints.

I've already added some code to Hitrava, which calculates and inserts 
the missing altitude information. If you like to include this code, I'm 
going to clean it up a little bit and try to use the distances 
(DistanceMeters) of the tracking point to do the interpolation. At the 
moment it uses only the trackingpoint numbers.

And yes, a command line argument would be fine.

Until now I've only found the XSD file, which define the TCX format. I'm 
not an expert for XSD files, but I think, that it only defines that the 
altitude elements are optional.

But however, I think it would be a good idea to have an optional 
argument in Hitrava, because there are at least 2 programs out there, 
which have problems with missing altitude elements. I think, that I've 
seen a third program with similar problems, but I can't remember it's name.


What do you like to do now?


With best regards,

Heiko


PS: I've not discussed this with the maintainers of QMapShack until now.

**Comment by CTHRU** [comment]
I don't know yet. I marked your request as an enhancement for now. I will see first if it can be added in an easy way, i'll add it.

**Comment by CTHRU** [comment]
Ok, it looks easy enough to add the last known altitude to every track point record. I will add it in the next release (coming soon).
