### ISSUE TITLE
[SUPPORT] File conversion not working

### ISSUE THREAD

**Issue by dostick** [CTHRU/Hitrava#29]
I've executed Hitrava trhough command line to conver one file and anything happens. I don't get any error message and the TCX is not generated.

Here's what I write in cmd:

python Hitrava.py -f HiTrack_1598504245000159851650400030001

Thanks for your help

**Comment by CTHRU** [comment]
Do I understand correctly that you don't get any logging message output?

You could start with the basic checks:

Check the python version by typing the following command at the terminal prompt.

> python --version

Try using Hitrava without any parameters. This should output the usage information.

> python Hitrava.py

Is this HiTrack file the only one that doesn't convert? If you want, you can (temporarily) share it here and I can have a look.

**Comment by dostick** [comment]
Hi again,

Checking python version seemed that python was not properly installed. I installed it from Microsoft Store on W10 and now it's working properly. Thanks a lot for your effort 👍
