### ISSUE TITLE
[SUPPORT] Using .tar files

### ISSUE THREAD

**Issue by dostick** [CTHRU/Hitrava#30]
Hi again,

I can't understand from the instructions if I have to crearte a .tar file with all my HiTrack files or if it is has a .tar file obtained from Huawei.

I've tried creating a .tar file with 7zip with all the Hitrack files and then execute the command as it is show in the instructions but is not working for me.

```
C:\Hitrava>python Hitrava.py -t huawei.tar
2020-09-24 11:03:32,720 - INFO - main - Hitrava version 3.6.1 (build 2009.1901) started with arguments ['-t', 'huawei.tar']
2020-09-24 11:03:32,720 - INFO - main - Running on Python version 3.8.6

C:\Hitrava>
```

The contents of the .tar file

![image](https://user-images.githubusercontent.com/71817709/94125585-d0af1880-fe56-11ea-80cf-58080d4f7237.png)

Thanks for your fast answer

**Comment by CTHRU** [comment]
The tar function was designed to convert the Hitrack files in an Android tar backup format.

If you want to create your own tar file, you will have to mimic the correct directory and file structure as follows:

- The HiTrack files must be in the following directory in the tar file:
>com.huawei.health/files
- The names of the HiTrack files must start with:
>HiTrack_

Alternatively, you could create a batch file that loops over all your HiTrack files and convert them using the --file option like you did for a single file.

**Comment by dostick** [comment]
I don't know how to create a batch file, but I've tested to mimic directory and file structure and works perfectly for me. Thanks again for you work and your fast support.
