### ISSUE TITLE
[SUPPORT] All My activites after 2.09.2020 are grayout in the HiTrava web. 

### ISSUE THREAD

**Issue by smonov** [CTHRU/Hitrava#32]
As you can see below All My activities after 2.09.2020 are grayout in the HiTrava web and can't be exported.
Why this is happening can someone propose a solution?

![image](https://user-images.githubusercontent.com/10730757/95503460-14a43080-09b4-11eb-9387-205c657440a4.png)

**Comment by CTHRU** [comment]
Well, it is 'normal'. It's currently an alpha version and I decided to release it in trial mode only for now. This means that some of the last activities will be greyed out. It's also mentioned in the alpha software notice [here](https://cthru.hopto.org/hitrava-web-alpha/).
I'm trying to continue to work on it in my spare time, I thank you for your patience.

**Comment by smonov** [comment]
Hi, 

In this case I can export the oldest 2 trackings only, out of 21.  It is more proper to say that only few tracking could be exported,  so I was wondering is it somehow different on my side and what is the criteria which trackings can be exported which not?

If the Python script is used instead of the web convert should I expect the same issue? 

Cheers,

**Comment by CTHRU** [comment]
I agree that in a case like yours where you recently started to use Huawei Health, the trial mode may look too restrictive. 
The python script version in this repository is 100% free for non-commercial use without any restrictions.
Using the script, you can convert all your available activities (i.e. the supported activity types, but the list is identical in script and web version).
