### ISSUE TITLE
[SUPPORT] Example command not worked

### ISSUE THREAD

**Issue by fu-hsi** [CTHRU/Hitrava#34]
Hi.
I tried this command from your advice:

> Hitrava.py --zip HiZip.zip --json_export

and I received usage tips:

> usage: Hitrava.py [-h] [-z ZIP] [-j JSON] [--json_export] [-f FILE] [-s {Walk,Run,Cycle,Swim_Pool,Swim_Open_Water}]
>                   [-t TAR] [--from_date FROM_DATE] [--pool_length POOL_LENGTH] [--tcx_insert_altitude_data]
>                   [--output_dir OUTPUT_DIR] [--use_original_filename] [--output_file_prefix OUTPUT_FILE_PREFIX]
>                   [--suppress_output_file_sequence] [--validate_xml] [--log_level {INFO,DEBUG}]

Any suggestions? What arguments are required? Why it is not worked?
I have "Motion path detail data & description\motion path detail data.json" file in zip package.

**Comment by fu-hsi** [comment]
I started command from bat file and from windows console (cmd).
After execute command new window appears...
Now I writing my own script in PHP, maybe I'll do it faster than I run a python script ;)

**Comment by CTHRU** [comment]
Do I understand correct that you got it working? If so, feel free to close the issue, If not, let me know.

**Comment by fu-hsi** [comment]
No, it doesn't work for me, but I writing my own script.

**Comment by CTHRU** [comment]
Strange. I be happy to help to sort it out though.

By any change, is there anything below the usage information? If so, it would state an unrecognized arguments message.

E.g. when you run the next command with an invalid parameter INVALID

>hitrava.py INVALID

You would get the following output.

>usage: Hitrava.py [-h] [-z ZIP] [-j JSON] [--json_export] [-f FILE] [-s {Walk,Run,Cycle,Swim_Pool,Swim_Open_Water}]
                  [-t TAR] [--from_date FROM_DATE] [--pool_length POOL_LENGTH] [--tcx_insert_altitude_data]
                  [--output_dir OUTPUT_DIR] [--use_original_filename] [--output_file_prefix OUTPUT_FILE_PREFIX]
                  [--suppress_output_file_sequence] [--validate_xml] [--log_level {INFO,DEBUG}]
**_Hitrava.py: error: unrecognized arguments: INVALID_**

Notice the last line in the output. If this is the case in your situation, you could recheck your command for any typing error.

I'm assuming that you are using a recent python version. You can check with the following command

>python --version

**Comment by fu-hsi** [comment]
After launch Run_Hitrava.cmd:
https://photos.app.goo.gl/Jp47TqQrZtpj5XEh8

I have HiZip.zip in the same directory.

**Comment by CTHRU** [comment]
I suspect it must have something to do with the 'Python Windows App' that you probably installed from the Windows Store. It looks like it doesn't take the command line parameters and just plainly executes the script without parameters.
I am not familiar with that Windows app at all. I suggest to install the regular python interpreter as explained in the [installation procedure in the README file here](https://github.com/CTHRU/Hitrava#step-1---install-python).

**Comment by CTHRU** [comment]
Yes, a quick StackOverflow search reveals that the WindowsApp doesn't take in parameters just like that.

It will be easier to use the suggested install procedure, I think.

You can have a [look here for more info](https://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t).

**Comment by fu-hsi** [comment]
Ah, OK :)
I already thought that I do not understand the simple thing...
Thanks.
