### ISSUE TITLE
[QUESTION] New project

### ISSUE THREAD

**Issue by fu-hsi** [CTHRU/Hitrava#35]
Hi.
Sorry, maybe this is wrong place to ask (can't find private email).
I just did it :) I wrote PHP script for parse Huawei motion path file to GPX.
I can't submit it to Strava now (duplicated activity) but I can read gpx from my run in GpxSee with HR and CAD.
Maybe you can give me some advices?
The last record with GPS location is:

> lat = 90.0; lon = -80.0

Does it happen to you? I removed it, but I wonder if it's the watch's fault?
Do you fill empty records by last measurement sensor values ​​or just put null?
I don't have any GPX files from any watch to compare data.
I have only one file from my new Huawei Band 4 Pro.
I waited about a day for my Huawei copy so it's probably not that bad.

Regards.

**Comment by CTHRU** [comment]
You're free to ask, but I think you will understand that I won't invest time in questions related to other projects. Thank you for your compréhension.
