### ISSUE TITLE
![no se puede exportar las actividades de octubre](https://user-images.githubusercontent.com/73828427/97885512-be62ad00-1d27-11eb-8591-c1609c408fc2.png)

### ISSUE THREAD

**Issue by chemiso21** [CTHRU/Hitrava#39]
![no se puede exportar las actividades de octubre](https://user-images.githubusercontent.com/73828427/97885512-be62ad00-1d27-11eb-8591-c1609c408fc2.png)
C:\Hitrava-4.0.0>Hitrava.py --zip HiZip.zip -- galaxias2414--json_export
Info - External library xmlschema could not be imported.
It is required when using the --validate_xml argument.
It can be installed using: pip install xmlschema
usage: Hitrava.py [-h] [-z ZIP] [-p PASSWORD] [-j JSON] [--json_export] [-f FILE]
                  [-s {Walk,Run,Cycle,Swim_Pool,Swim_Open_Water}] [-t TAR] [--from_date FROM_DATE]
                  [--pool_length POOL_LENGTH] [--tcx_insert_altitude_data] [--output_dir OUTPUT_DIR]
                  [--use_original_filename] [--output_file_prefix OUTPUT_FILE_PREFIX]
                  [--suppress_output_file_sequence] [--validate_xml] [--log_level {INFO,DEBUG}]
Hitrava.py: error: unrecognized arguments: -- xxxxxxxxxxxx--json_export

_Originally posted by @chemiso21 in https://github.com/CTHRU/Hitrava/issues/38#issuecomment-720542001_

**Comment by chemiso21** [comment]
![Nueva imagen (1)](https://user-images.githubusercontent.com/73828427/97890458-d9d0b680-1d2d-11eb-9883-094dd092c1ae.png)
[HUAWEI_HEALTH_20201102170057.zip](https://github.com/CTHRU/Hitrava/files/5476285/HUAWEI_HEALTH_20201102170057.zip)

**Comment by CTHRU** [comment]
I answered your questions in your previous issue #38 in this [comment](https://github.com/CTHRU/Hitrava/issues/38#issuecomment-720673291).

I will close this issue to not have duplicate issues.
