### ISSUE TITLE
[Mobile app] Mobile app with automatic activity upload to Strava

### ISSUE THREAD

**Issue by EnergyStaRed** [CTHRU/Hitrava#44]
It's not very practical to export activities from Huawei Health then send to PC, convert using Hitrava and then upload to Strava.
Much better would be automatic export, transform and upload via mobile app. As soon as you complete an activity it should automatically be exported to Hitrava and further uploaded to Strava.

**Comment by JonnIEnglish** [comment]
Agreed, just not sure how the best way to go about that would be...
