### ISSUE TITLE
question about pool length

### ISSUE THREAD

**Issue by dan1967** [CTHRU/Hitrava#53]
hello,
I have question about your program.

I try understand your code, for my improvements..
For swimming activity, you have command line argument (**--pool_length**). 
If pool length is in json data (**['wearSportData']['swim_pool_length']**), you rewrite command line value?

And second question. 
For next question about your code...
What is better?
- question in issue
- discussions
- private message/email...?

**Comment by CTHRU** [comment]
Hi Dan,

If you use the --pool-length parameter, it should override the info from the json file. If not, let me know, it's a bug.

As for your second question, with the introduction of GitHub discussions, I thought I'd give it a try and reserve the issues section for bugs and feature requests. But it's not all that important, go ahead and ask your question.
