### ISSUE TITLE
Can't upload Workouts 2 last month - Hitrava Web trial limitations

### ISSUE THREAD

**Issue by horaz0815** [CTHRU/Hitrava#58]
Hello!

I have always the problem, that i can't convert always the last 2 month, the month before is no problem, you can see it in the picture, i can't select the workouts..

Thanks
Mike
![Screenshot_20210223-115216](https://user-images.githubusercontent.com/79513997/108834121-0f93f680-75ce-11eb-9ef5-dc528f7af760.jpg)

**Comment by EijaAkib** [comment]
I'm having the problem as your. i cant upload for the current month and some of the previous monthas well. anyone can help me on this matters as well. thank you in advanced.
![WhatsApp Image 2021-03-02 at 19 28 16](https://user-images.githubusercontent.com/79911872/109642598-274f1a00-7b8e-11eb-80a2-a55b2cde8f95.jpeg)

**Comment by CTHRU** [comment]
Well, it is 'normal'. It's currently an alpha version and I decided to release it in trial mode only for now. This means that some of the last activities will be greyed out. It's also mentioned in the alpha software notice [here](https://cthru.hopto.org/hitrava-web-alpha/).
I'm trying to continue to work on it in my spare time, unfortunately due to personal reasons, I'm not able to continue to work on it for now. I thank you for your patience.
See also #32.

**Comment by EijaAkib** [comment]
ooooo ok..Thank you so much for your kindand very fast reply...does it
means next month i will be able to upload for february data?

**Comment by CTHRU** [comment]
Yes, the web version only limits some of the last activities. As an alternative, you can use the script version from this repository, which has no restrictions whatsoever.

**Comment by EijaAkib** [comment]
do you mind to guide how to do that?..im not really good at it..
Thank again.

**Comment by CTHRU** [comment]
You can find the [installation procedure](https://github.com/CTHRU/Hitrava#installation) for the script version on [the main README page of this repository](https://github.com/CTHRU/Hitrava).

Reading further on the same page will lead you to the [conversion procedure](https://github.com/CTHRU/Hitrava#how-to-convert-your-health-activities-and-import-them-in-strava).

I understand it might be technical (hence the reason of existence of the web version). If so, just stick for now with the web version.

**Comment by EijaAkib** [comment]
Thanks, I'll take a look.
