### ISSUE TITLE
extract only heart rate data

### ISSUE THREAD

**Issue by chemiso21** [CTHRU/Hitrava#59]
hello, the question is simple. Is there a way to extract from the huawei data file of an honor magic wacht 2 watch, only the heart rate data. Thanks.
**Describe the bug**

**Logs**
If applicable, add logging and error information from the application.
To enable full logging, add the command line argument **--log_level DEBUG** when running the program.

**Files**
If applicable, add relevant input and output files (by dragging them here).
For JSON conversions, you can use the **--json_export** command line argument. This will generate a separate .json file with the original Huawei HiTrack data for each activity that you can add here. 

Note: be aware that your fitness activity files (may) contain personal data. We will notify that you can remove the attached files from your report as soon as we have downloaded them. We will ONLY use the files for debugging purposes.

**Screenshots**

**Additional context**

**Comment by CTHRU** [comment]
I assume you mean the data of the continuous heart rate tracking independent from your sport activities.
Short answer, yes, the data is available in the Huawei ZIP file in the following file:
> Health detail data & description\health detail data.json

**Comment by chemiso21** [comment]
ok and is there a way to use or convert them to incorporate them into strava on a garmin recorded route. Thanks.

**Comment by CTHRU** [comment]
I guess that would require you to export the route you recorded with your Garmin (TCX) and then merge the corresponding heart rate information from Huawei based on timestamp into the Garmin TCX. I guess it's feasible but definitely a one-off, no?

**Comment by chemiso21** [comment]
I'll try. Thanks a lot.

**Comment by paranoidandy** [comment]
> I assume you mean the data of the continuous heart rate tracking independent from your sport activities. Short answer, yes, the data is available in the Huawei ZIP file in the following file:
> 
> > Health detail data & description\health detail data.json

Sorry to necro an old issue but you seem to know the most out there on the subject - If I have a rooted device/emulator, is it possible to read the 24 hour heart rate data (and stress data, spo2 data etc etc) from the android app data in a similar way? Thanks!

**Comment by CTHRU** [comment]
> If I have a rooted device/emulator, is it possible to read the 24 hour heart rate data (and stress data, spo2 data etc etc) from the android app data in a similar way? Thanks!

To my (old) knowlegde, the app did only create a HiTrack file containing data from a recorded workout (and only if you explicitly viewed the details of the workout). I don't know if and where the app would store the continuous measured data from the watch in a local file.
