### ISSUE TITLE
[SUPPORT] file not found error

### ISSUE THREAD

**Issue by Sevrossi** [CTHRU/Hitrava#65]
Hello,
Just tried to update my old HiTrava release (3.6.1) to the 5.0 but I can't make it working. I had firt a python library xmlschema missing but now I get this message

> 2021-05-15 11:03:01,642 - INFO - main - Running on Python version 3.9.5
>
>Traceback (most recent call last):
>  File "C:\Hitrava-5.0.0\Hitrava.py", line 2127, in <module>
>    main()
>  File "C:\Hitrava-5.0.0\Hitrava.py", line 2109, in main
>    json_filename = HiZip.extract_json(args.zip, args.output_dir, args.password)
>  File "C:\Hitrava-5.0.0\Hitrava.py", line 1127, in extract_json
>    completed_process = subprocess.run(unzip_cmd,
>  File "C:\Users\sevro\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
>    with Popen(*popenargs, **kwargs) as process:
>  File "C:\Users\sevro\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
>    self._execute_child(args, executable, preexec_fn, close_fds,
>  File "C:\Users\sevro\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
>    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

How to resolve ?

Regards

**Comment by CTHRU** [comment]
It's probably the 7-zip executable that is missing from the installation folder.

You can find more info in the [installation instructions here](https://github.com/CTHRU/Hitrava#step-3---download-and-extract-stand-alone-7-zip).

If your problem isn't solved, just let me know. If it is, you can let me know by closing this issue.

**Comment by Sevrossi** [comment]
Working perfectly, thanks. Sorry for not having re-read all the installation procedure ^^

**Comment by CTHRU** [comment]
Not a problem at all, glad you asked and that it's solved. Happy converting.
