### ISSUE TITLE
Activities grayed out in Hitrava web - can't conver them

### ISSUE THREAD

**Issue by MichaelF38** [CTHRU/Hitrava#68]
Hi, I have an issue which you may be able to help with! 
I'm trying to convert an activity from Huawei Health that shows properly in the app except for a message that says: "This activity won't be recorded in your personnal results because some data is missing or abnormal".. but the activity seems to have been recorded ok (cf screenshots attached) - the only caveat is I recorded this on a Huawei GT2 Pro using running mode where I was actually paragliding.. 

Anyways I'd like to import it to strava or some other platform.
In Hitrava web as you can see in the screenshots I cannot select the activity: it appears as grayed out (like 2 other activities in fact..) - the only one I can select is a running sessing couple weeks back..

I attached the json.
Any help is welcome!
thanks
[motion path detail data.zip](https://github.com/CTHRU/Hitrava/files/6631215/motion.path.detail.data.zip)
![Screenshot_20210610_135939_com huawei health](https://user-images.githubusercontent.com/75612030/121522072-0865ec80-c9f5-11eb-9e8b-0ad6fc166f40.jpg)
![Screenshot_20210610_135948_com huawei health](https://user-images.githubusercontent.com/75612030/121522076-08fe8300-c9f5-11eb-8b42-f666f19226a1.jpg)
![Screenshot_20210610_140003_com huawei health](https://user-images.githubusercontent.com/75612030/121522077-08fe8300-c9f5-11eb-9080-d6cf6e3cf40b.jpg)
![Screenshot_20210610_140006_com huawei health](https://user-images.githubusercontent.com/75612030/121522079-09971980-c9f5-11eb-9173-d38cac87f9b0.jpg)
![Screenshot_20210610_140010_com huawei health](https://user-images.githubusercontent.com/75612030/121522083-0a2fb000-c9f5-11eb-93c0-fd0678bf1aab.jpg)
![Screenshot_20210610_140050_com android chrome](https://user-images.githubusercontent.com/75612030/121522084-0ac84680-c9f5-11eb-8f7f-4dc5e962c7ce.jpg)

**Comment by CTHRU** [comment]
Bonjour,

La version web n'existe qu' en version d'essai. Probablement ca c'est la cause. Voir aussi #58.
