### ISSUE TITLE
[SUPPORT] Does not work on latest export?

### ISSUE THREAD

**Issue by mist3r3** [CTHRU/Hitrava#71]
I can't make it work. It seems the format is not really the same anymore..

**Comment by CTHRU** [comment]
Hello, that sounds unfortunate. Should you have any example file tht you don't mind sharing of a single activity / log output of Hitrava that doesn't convert, I'd be happy to investigate if / what could be done.

**Comment by CTHRU** [comment]
Hi, I just checked with my own data after I requested it based on your message.
With my exported data, everything works just fine.
Can you double check from your side that you used the `motion path detail data.json` from your exported zip file?
If the problem persists, I'd be glad to investigate further if you can provide me with a bit more detail info (see my message above).

**Comment by mist3r3** [comment]
Hi, I'm not sure how, now it's working, I restarted my laptop and made it work somehow. This is great thanks!

**Comment by CTHRU** [comment]
Great! Glad to hear it works. Thanks for letting us now.
